backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

publish_mode: simple

editor:
  preview: true

collections:
  - name: "countries"
    label: "Countries"
    label_singular: "Country"
    folder: "data/countries"
    create: true
    format: "json"
    extension: "json"
    identifier_field: code
    slug: "{{code}}"
    fields:
      - {label: "Code (ISO, e.g. CA)", name: "code", widget: "string"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Flag URL", name: "flag", widget: "string", hint: "Use https://flagcdn.com/w320/xx.png or upload to /uploads and paste path"}
      - {label: "Video URL or Embed", name: "video_embed", widget: "string", required: false}
      - label: "Images"
        name: "images"
        widget: "list"
        field: {label: "Image URL", name: "image", widget: "string"}
      - {label: "Population", name: "population", widget: "number", required: false}
      - {label: "Area (km²)", name: "area_km2", widget: "number", required: false}
      - {label: "Highest Point (m)", name: "highest_point_m", widget: "number", required: false}
      - {label: "Currency", name: "currency", widget: "string", required: false}
      - label: "Animals"
        name: "animals"
        widget: "list"
        field: {label: "Animal", name: "animal", widget: "string"}
      - label: "languages"
        name: "languages"
        widget: "list"
        field: {label: "languages", name: "languages", widget: "string"}
      - {label: "Geographic Location", name: "location", widget: "text", required: false}
      - {label: "Facts", name: "facts", widget: "text", required: false}
      - {label: "History", name: "history", widget: "text", required: false}
